FROM docker.elastic.co/logstash/logstash:6.3.1

LABEL maintainer="pkriadis@alumni.harvard.edu"

ADD logstash.yml /usr/share/logstash/config/logstash.yml
ADD logstash.conf /usr/share/logstash/pipeline/logstash.conf
